#!/usr/bin/env python

from accTest._testing import fakes

screenplayText = \
"""
segfault n/a
"""

screenplay = fakes.Screenplay.fromTextBuffer(screenplayText)
imp = fakes.Impersonator()
imp.act(screenplay)
